name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Extract version from tag or input
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        fi
        
    - name: Update version in build.gradle.kts
      run: |
        sed -i 's/version = ".*"/version = "${{ steps.version.outputs.version }}"/' build.gradle.kts
        
    - name: Build plugin
      run: ./gradlew buildPlugin --no-daemon
      
    - name: Verify plugin
      run: ./gradlew verifyPlugin --no-daemon
      
    - name: Create release notes
      id: release_notes
      run: |
        cat > release_notes.md << 'EOF'
        ## What's New in v${{ steps.version.outputs.version }}
        
        ### Features
        - Auto-completion for slash commands and file references
        - Enhanced markdown rendering with flexmark-java
        - GitHub Flavored Markdown support (tables, strikethrough, task lists)
        - Improved edit tool display with collapsible preview
        - Async file search with glob pattern matching
        
        ### Improvements  
        - Better process management for stop functionality
        - IntelliJ-style UI with proper positioning
        - Keyboard navigation for completion popup
        - Performance optimizations for file search
        
        ### Technical
        - Replaced custom markdown parser with industry-standard flexmark-java
        - Added comprehensive completion system with slash commands and file references
        - Enhanced UI components with better error handling
        
        Built with Claude Code and IntelliJ Platform SDK
        EOF
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Claude Code Chat v${{ steps.version.outputs.version }}
        body_path: release_notes.md
        files: |
          build/distributions/*.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload plugin to artifact
      uses: actions/upload-artifact@v4
      with:
        name: claude-code-chat-plugin-v${{ steps.version.outputs.version }}
        path: build/distributions/*.zip
        retention-days: 90